### ISSUE TITLE
Use of list for filenames not working

### ISSUE THREAD

**Issue by gciCeleste** [xebialabs-community/xlr-variable-setter-plugin#1]
instead of allowing use of drop down to select a variable of type list - it attempts to create a variable with the name entered

**Comment by ladamato** [comment]
Tested using the newest 1.0.4 release and works for this use case:
1. Create a variable of type List
2. Add file names
3. When setting the value for 'List of file names:', click the drop down arrow and choose your list variable. 

Celeste - if your use case is different than this scenario, let me know - Thanks, Lynn
