### ISSUE TITLE
trying to run in XLR 9.0.5, getting exception about newer Java runtime

### ISSUE THREAD

**Issue by databigot** [xebialabs-community/xlr-variable-setter-plugin#7]
Hi. 

Exception during execution: java.lang.UnsupportedClassVersionError: java.lang.UnsupportedClassVersionError: setvariables/DynamicVariables has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0 in <script> at line number 15

Any advice?

**Comment by magichome** [comment]
What version of java are you running?

**Comment by acrozes** [comment]
Hi,

Same error using the last docker image: 

Name
    xebialabs/xl-release
Summary
    XL Release
Description
    Enterprise-scale Application Release Automation for any environment
Source URL
    https://www.xebialabs.com/xl-release 
Author
    XebiaLabs Development <docker@xebialabs.com>
Built
    9 days ago
Digest
    sha256:8f47911b6ef9363428b62324d7a15f628514688db8847072dc87da0031d89c81
Identifier
    sha256:9bd46a9632f39217385ec8998fbe7aef82b3890582ca491b356cb3f46f8202bc

Labels
    maintainer=docker@xebialabs.com 
    release=1 
    summary=XL Release 
    url=https://www.xebialabs.com/xl-release 
    vendor=XebiaLabs 
    version=9.5.3 


### Error: 
Exception during execution: java.lang.UnsupportedClassVersionError: java.lang.UnsupportedClassVersionError: setvariables/DynamicVariables has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0 in <script> at line number 15

**Comment by ladamato** [comment]
Sorry about that! The release build is created in Travis so we are now forcing Java 8 compilation. There is a new release up now. I've downloaded and tested the actual release artifact and it seems good. Thanks for bringing this to our attention. Let us know if you run into any other issues.

**Comment by acrozes** [comment]
Thank you ! 
Fixed for me.

**Comment by databigot** [comment]
Fixed for me.  Thanks!
